In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
df = pd.read_csv('C:/Users/Kaushik/Documents/Kaggle Datasets/Machine Learning/Classification Datasets/Rain in Australia/weatherAUS.csv')
print('Size of weather data frame is :',df.shape)

Size of weather data frame is : (142193, 24)


In [3]:
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  12/1/2008   Albury     13.4     22.9       0.6          NaN       NaN   
1  12/2/2008   Albury      7.4     25.1       0.0          NaN       NaN   
2  12/3/2008   Albury     12.9     25.7       0.0          NaN       NaN   
3  12/4/2008   Albury      9.2     28.0       0.0          NaN       NaN   
4  12/5/2008   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   
3          NE           24.0         SE  ...        16.0       1017.6   
4           W           41.0        ENE  ...        33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 24 columns]

In [4]:
df.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  141556.000000  141871.000000  140787.000000  81350.000000   
mean       12.186400      23.226784       2.349974      5.469824   
std         6.403283       7.117618       8.465173      4.188537   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.800000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  74377.000000  132923.000000  140845.000000  139563.000000   
mean       7.624853      39.984292      14.001988      18.637576   
std        3.781525      13.588801       8.893337       8.803345   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.900000      31.000000       7.000000      13.000000   
50%        8.500000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm    Pressure9am    Pressure3pm  \
count  140419.000000  138583.000000  128179.000000  128212.000000   
mean       68.843810      51.482606    1017.653758    1015.258204   
std        19.051293      20.797772       7.105476       7.036677   
min         0.000000       0.000000     980.500000     977.100000   
25%        57.000000      37.000000    1012.900000    1010.400000   
50%        70.000000      52.000000    1017.600000    1015.200000   
75%        83.000000      66.000000    1022.400000    1020.000000   
max       100.000000     100.000000    1041.000000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am        Temp3pm        RISK_MM  
count  88536.000000  85099.000000  141289.000000  139467.000000  142193.000000  
mean       4.437189      4.503167      16.987509      21.687235       2.360682  
std        2.887016      2.720633       6.492838       6.937594       8.477969  
min        0.000000      0.000000      -7.200000      -5.400000       0.000000  
25%        1.000000      2.000000      12.300000      16.600000       0.000000  
50%        5.000000      5.000000      16.700000      21.100000       0.000000  
75%        7.000000      7.000000      21.600000      26.400000       0.800000  
max        9.000000      9.000000      40.200000      46.700000     371.000000

In [5]:
df.count()

Date             142193
Location         142193
MinTemp          141556
MaxTemp          141871
Rainfall         140787
Evaporation       81350
Sunshine          74377
WindGustDir      132863
WindGustSpeed    132923
WindDir9am       132180
WindDir3pm       138415
WindSpeed9am     140845
WindSpeed3pm     139563
Humidity9am      140419
Humidity3pm      138583
Pressure9am      128179
Pressure3pm      128212
Cloud9am          88536
Cloud3pm          85099
Temp9am          141289
Temp3pm          139467
RainToday        140787
RISK_MM          142193
RainTomorrow     142193
dtype: int64

In [6]:
def missing_values_perc():
    temp_dict = dict()
    for i in df.columns:
        if df[i].isnull().sum()>0:
            temp_dict[i] = round(((df[i].isnull().sum())*100/df[i].count()),2)
    return temp_dict         

In [7]:
sorted(missing_values_perc().items() ,  key=lambda x: x[1]  )

[('MaxTemp', 0.23),
 ('MinTemp', 0.45),
 ('Temp9am', 0.64),
 ('WindSpeed9am', 0.96),
 ('Rainfall', 1.0),
 ('RainToday', 1.0),
 ('Humidity9am', 1.26),
 ('WindSpeed3pm', 1.88),
 ('Temp3pm', 1.95),
 ('Humidity3pm', 2.6),
 ('WindDir3pm', 2.73),
 ('WindGustSpeed', 6.97),
 ('WindGustDir', 7.02),
 ('WindDir9am', 7.58),
 ('Pressure3pm', 10.9),
 ('Pressure9am', 10.93),
 ('Cloud9am', 60.6),
 ('Cloud3pm', 67.09),
 ('Evaporation', 74.79),
 ('Sunshine', 91.18)]

In [8]:
df = df.drop(columns=['Sunshine','Evaporation','Cloud3pm','Cloud9am','Location','RISK_MM','Date'],axis=1)

In [9]:
sorted(missing_values_perc().items() ,  key=lambda x: x[1]  )

[('MaxTemp', 0.23),
 ('MinTemp', 0.45),
 ('Temp9am', 0.64),
 ('WindSpeed9am', 0.96),
 ('Rainfall', 1.0),
 ('RainToday', 1.0),
 ('Humidity9am', 1.26),
 ('WindSpeed3pm', 1.88),
 ('Temp3pm', 1.95),
 ('Humidity3pm', 2.6),
 ('WindDir3pm', 2.73),
 ('WindGustSpeed', 6.97),
 ('WindGustDir', 7.02),
 ('WindDir9am', 7.58),
 ('Pressure3pm', 10.9),
 ('Pressure9am', 10.93)]

In [10]:
df = df.dropna(how='any')

In [11]:
sorted(missing_values_perc().items() ,  key=lambda x: x[1]  )

[]

In [12]:
from scipy import stats
z = np.abs(stats.zscore(df._get_numeric_data()))

In [13]:
print(z)

[[0.11756741 0.10822071 0.20666127 ... 1.14245477 0.08843526 0.04787026]
 [0.84180219 0.20684494 0.27640495 ... 1.04184813 0.04122846 0.31776848]
 [0.03761995 0.29277194 0.27640495 ... 0.91249673 0.55672435 0.15688743]
 ...
 [1.44940294 0.23548728 0.27640495 ... 0.58223051 1.03257127 0.34701958]
 [1.16159206 0.46462594 0.27640495 ... 0.25166583 0.78080166 0.58102838]
 [0.77784422 0.4789471  0.27640495 ... 0.2085487  0.37167606 0.56640283]]


In [14]:
df = df[(z<3).all(axis=1)]

In [15]:
print(df.shape)

(107868, 17)


In [16]:
df.describe()

MinTemp        MaxTemp       Rainfall  WindGustSpeed  \
count  107868.000000  107868.000000  107868.000000  107868.000000   
mean       12.564709      23.653387       1.482925      39.773733   
std         6.251908       6.917637       3.904974      11.967334   
min        -6.000000       4.100000       0.000000       7.000000   
25%         8.000000      18.300000       0.000000      31.000000   
50%        12.300000      23.200000       0.000000      39.000000   
75%        17.100000      28.700000       0.600000      48.000000   
max        31.400000      44.600000      28.000000      80.000000   

        WindSpeed9am   WindSpeed3pm    Humidity9am    Humidity3pm  \
count  107868.000000  107868.000000  107868.000000  107868.000000   
mean       14.692504      19.064199      67.381346      50.343930   
std         7.663969       8.017655      18.511889      20.404615   
min         2.000000       2.000000      11.000000       0.000000   
25%         9.000000      13.000000      56.000000      36.000000   
50%        13.000000      19.000000      68.000000      51.000000   
75%        20.000000      24.000000      81.000000      64.000000   
max        39.000000      44.000000     100.000000     100.000000   

         Pressure9am    Pressure3pm        Temp9am        Temp3pm  
count  107868.000000  107868.000000  107868.000000  107868.000000  
mean     1017.754662    1015.345157      17.399578      22.143784  
std         6.733285       6.691289       6.323997       6.766673  
min       996.400000     994.200000      -1.100000       3.200000  
25%      1013.200000    1010.600000      12.700000      17.000000  
50%      1017.700000    1015.200000      17.000000      21.600000  
75%      1022.300000    1019.900000      22.000000      26.900000  
max      1038.500000    1035.900000      36.500000      42.600000

In [17]:
df['RainToday'].replace({'No': 0, 'Yes': 1},inplace = True)
df['RainTomorrow'].replace({'No': 0, 'Yes': 1},inplace = True)

In [18]:
categorical_columns = ['WindGustDir', 'WindDir3pm', 'WindDir9am']
for col in categorical_columns:
    print(np.unique(df[col]))

['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW']


In [19]:
# transform the categorical columns
df = pd.get_dummies(df, columns=categorical_columns)
df.iloc[4:9]

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
4     17.5     32.3       1.0           41.0           7.0          20.0   
5     14.6     29.7       0.2           56.0          19.0          24.0   
6     14.3     25.0       0.0           50.0          20.0          24.0   
7      7.7     26.7       0.0           35.0           6.0          17.0   
8      9.7     31.9       0.0           80.0           7.0          28.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir9am_NNW  \
4         82.0         33.0       1010.8       1006.0  ...               0   
5         55.0         23.0       1009.2       1005.4  ...               0   
6         49.0         19.0       1009.6       1008.2  ...               0   
7         48.0         19.0       1013.4       1010.1  ...               0   
8         42.0          9.0       1008.9       1003.6  ...               0   

   WindDir9am_NW  WindDir9am_S  WindDir9am_SE  WindDir9am_SSE  WindDir9am_SSW  \
4              0             0              0               0               0   
5              0             0              0               0               0   
6              0             0              0               0               0   
7              0             0              0               1               0   
8              0             0              1               0               0   

   WindDir9am_SW  WindDir9am_W  WindDir9am_WNW  WindDir9am_WSW  
4              0             0               0               0  
5              0             1               0               0  
6              1             0               0               0  
7              0             0               0               0  
8              0             0               0               0  

[5 rows x 62 columns]

In [20]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaler.fit(df)
df = pd.DataFrame(scaler.transform(df), index=df.index, columns=df.columns)
df.iloc[4:10]

MinTemp   MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
4  0.628342  0.696296  0.035714       0.465753      0.135135      0.428571   
5  0.550802  0.632099  0.007143       0.671233      0.459459      0.523810   
6  0.542781  0.516049  0.000000       0.589041      0.486486      0.523810   
7  0.366310  0.558025  0.000000       0.383562      0.108108      0.357143   
8  0.419786  0.686420  0.000000       1.000000      0.135135      0.619048   
9  0.510695  0.641975  0.050000       0.287671      0.351351      0.214286   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir9am_NNW  \
4     0.797753         0.33     0.342043     0.282974  ...             0.0   
5     0.494382         0.23     0.304038     0.268585  ...             0.0   
6     0.426966         0.19     0.313539     0.335731  ...             0.0   
7     0.415730         0.19     0.403800     0.381295  ...             0.0   
8     0.348315         0.09     0.296912     0.225420  ...             0.0   
9     0.528090         0.27     0.251781     0.275779  ...             0.0   

   WindDir9am_NW  WindDir9am_S  WindDir9am_SE  WindDir9am_SSE  WindDir9am_SSW  \
4            0.0           0.0            0.0             0.0             0.0   
5            0.0           0.0            0.0             0.0             0.0   
6            0.0           0.0            0.0             0.0             0.0   
7            0.0           0.0            0.0             1.0             0.0   
8            0.0           0.0            1.0             0.0             0.0   
9            0.0           1.0            0.0             0.0             0.0   

   WindDir9am_SW  WindDir9am_W  WindDir9am_WNW  WindDir9am_WSW  
4            0.0           0.0             0.0             0.0  
5            0.0           1.0             0.0             0.0  
6            1.0           0.0             0.0             0.0  
7            0.0           0.0             0.0             0.0  
8            0.0           0.0             0.0             0.0  
9            0.0           0.0             0.0             0.0  

[6 rows x 62 columns]

In [21]:
from sklearn.feature_selection import SelectKBest, chi2
X = df.loc[:,df.columns!='RainTomorrow']
y = df[['RainTomorrow']]
selector = SelectKBest(chi2, k=3)
selector.fit(X, y)
X_new = selector.transform(X)
print(X.columns[selector.get_support(indices=True)]) #top 3 columns

Index(['Rainfall', 'Humidity3pm', 'RainToday'], dtype='object')


In [22]:
df.head()

MinTemp   MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0  0.518717  0.464198  0.021429       0.506849      0.486486      0.523810   
1  0.358289  0.518519  0.000000       0.506849      0.054054      0.476190   
2  0.505348  0.533333  0.000000       0.534247      0.459459      0.571429   
3  0.406417  0.590123  0.000000       0.232877      0.243243      0.166667   
4  0.628342  0.696296  0.035714       0.465753      0.135135      0.428571   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  ...  WindDir9am_NNW  \
0     0.674157         0.22     0.268409     0.309353  ...             0.0   
1     0.370787         0.25     0.337292     0.326139  ...             1.0   
2     0.303371         0.30     0.266033     0.347722  ...             0.0   
3     0.382022         0.16     0.503563     0.446043  ...             0.0   
4     0.797753         0.33     0.342043     0.282974  ...             0.0   

   WindDir9am_NW  WindDir9am_S  WindDir9am_SE  WindDir9am_SSE  WindDir9am_SSW  \
0            0.0           0.0            0.0             0.0             0.0   
1            0.0           0.0            0.0             0.0             0.0   
2            0.0           0.0            0.0             0.0             0.0   
3            0.0           0.0            1.0             0.0             0.0   
4            0.0           0.0            0.0             0.0             0.0   

   WindDir9am_SW  WindDir9am_W  WindDir9am_WNW  WindDir9am_WSW  
0            0.0           1.0             0.0             0.0  
1            0.0           0.0             0.0             0.0  
2            0.0           1.0             0.0             0.0  
3            0.0           0.0             0.0             0.0  
4            0.0           0.0             0.0             0.0  

[5 rows x 62 columns]

In [23]:
#Logistic Regression 

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_logreg = LogisticRegression(random_state=0)
clf_logreg.fit(X_train,y_train.values.ravel())
y_pred = clf_logreg.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)

C:\Users\Kaushik\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Accuracy : 0.8510030778358735
Time taken : 1.1269845962524414


In [24]:
%%time
accuracy_score(y_train,clf_logreg.predict(X_train))

Wall time: 18 ms


0.8532898233643589

In [25]:
#Random Forest Classifier 

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_rf = RandomForestClassifier(n_estimators=100, max_depth=4,random_state=0)
clf_rf.fit(X_train,y_train.values.ravel())
y_pred = clf_rf.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)

Accuracy : 0.8191864130233248
Time taken : 3.2463200092315674


In [26]:
#Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train,y_train.values.ravel())
y_pred = clf_dt.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)

Accuracy : 0.7917454666814996
Time taken : 1.5807545185089111


In [27]:
#Support Vector Machine
"""
from sklearn import svm
from sklearn.model_selection import train_test_split

t0=time.time()
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
clf_svc = svm.SVC(kernel='linear')
clf_svc.fit(X_train,y_train.values.ravel())
y_pred = clf_svc.predict(X_test)
score = accuracy_score(y_test,y_pred)
print('Accuracy :',score)
print('Time taken :' , time.time()-t0)"""

"\nfrom sklearn import svm\nfrom sklearn.model_selection import train_test_split\n\nt0=time.time()\nX_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)\nclf_svc = svm.SVC(kernel='linear')\nclf_svc.fit(X_train,y_train.values.ravel())\ny_pred = clf_svc.predict(X_test)\nscore = accuracy_score(y_test,y_pred)\nprint('Accuracy :',score)\nprint('Time taken :' , time.time()-t0)"

In [28]:
dtypes_def = df.dtypes.reset_index()
dtypes_def.columns = ['Count','Column Type']
dtypes_def.groupby('Column Type').aggregate('count').reset_index()

Column Type  Count
0     float64     62

In [29]:
numeric_features = list(X.columns)
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features)])

In [30]:

# Our algorithms, by from the easiest to the hardest to intepret.
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost.sklearn import XGBClassifier

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

In [31]:
# Now we can define our 4 models as sklearn Pipeline object, containing our preprocessing step and training of one given algorithm.

# Logistic Regression
lr_model = Pipeline([("preprocessor", preprocessor), 
                     ("model", LogisticRegression(class_weight="balanced", solver="liblinear", random_state=42))])

# Decision Tree
dt_model = Pipeline([("preprocessor", preprocessor), 
                     ("model", DecisionTreeClassifier(class_weight="balanced"))])

# Random Forest
rf_model = Pipeline([("preprocessor", preprocessor), 
                     ("model", RandomForestClassifier(class_weight="balanced", n_estimators=100, n_jobs=-1))])

# XGBoost
xgb_model = Pipeline([("preprocessor", preprocessor), 
                      # Add a scale_pos_weight to make it balanced
                      ("model", XGBClassifier(scale_pos_weight=(1 - y.mean()), n_jobs=-1))])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=.3, random_state=42)

In [33]:
"""%%time
k_range = range(1,30)
param_grid = dict(model__C = k_range)
gs = GridSearchCV(lr_model, param_grid, n_jobs=-1, cv=10, scoring="accuracy")
gs.fit(X_train, y_train)  """  

'%%time\nk_range = range(1,30)\nparam_grid = dict(model__C = k_range)\ngs = GridSearchCV(lr_model, param_grid, n_jobs=-1, cv=10, scoring="accuracy")\ngs.fit(X_train, y_train)  '

In [34]:
"""print(gs.best_params_)
print(gs.best_score_)"""

'print(gs.best_params_)\nprint(gs.best_score_)'

In [35]:
"""accuracy_score(y_train,gs.predict(X_train))"""

'accuracy_score(y_train,gs.predict(X_train))'

In [36]:
"""lr_model.set_params(**gs.best_params_)"""

'lr_model.set_params(**gs.best_params_)'

In [37]:
"""lr_model.get_params("model")"""

'lr_model.get_params("model")'

In [38]:
"""lr_model.fit(X_train, y_train)"""

'lr_model.fit(X_train, y_train)'

In [39]:
"""y_pred = lr_model.predict(X_test)"""

'y_pred = lr_model.predict(X_test)'

In [40]:
"""accuracy_score(y_test, y_pred)"""

'accuracy_score(y_test, y_pred)'

In [41]:
"""print(classification_report(y_test, y_pred))"""

'print(classification_report(y_test, y_pred))'

In [42]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

slvr = ['liblinear', 'newton-cg', 'sag', 'saga' , 'lbfgs']
multi_cls = ['ovr', 'multinomial', 'auto']

#pnlty = ['l1', 'l2', 'none']


krn = ['linear','poly','rbf','sigmoid']
rng_C = np.arange(1,52,10)
rng_deg = np.arange(3,8)
rng_co = np.arange(0.001,10,0.5)
rng_gam = ['auto','scale']

In [43]:
"""%%time
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC,LinearSVC
b_score = 0
for i in krn:   
    for j in rng_C:
        for k in rng_deg:
            for x in rng_co:
                for y in rng_gam:
                    test_svm_mod = SVC(kernel=i)
                    test_svm_mod.fit(X_train,y_train.values.ravel())
                    accuracy_scr = accuracy_score(y_test, test_svm_mod.predict(X_test))
                    if b_score < accuracy_scr:
                        b_score =  accuracy_scr
                        bi = i 
                        bj = j 
                        bk = k
                        bx = x
                        by = y
print(b_score, bi, bj, bk, bx, by)"""           

'%%time\nfrom sklearn import svm\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.svm import SVC,LinearSVC\nb_score = 0\nfor i in krn:   \n    for j in rng_C:\n        for k in rng_deg:\n            for x in rng_co:\n                for y in rng_gam:\n                    test_svm_mod = SVC(kernel=i)\n                    test_svm_mod.fit(X_train,y_train.values.ravel())\n                    accuracy_scr = accuracy_score(y_test, test_svm_mod.predict(X_test))\n                    if b_score < accuracy_scr:\n                        b_score =  accuracy_scr\n                        bi = i \n                        bj = j \n                        bk = k\n                        bx = x\n                        by = y\nprint(b_score, bi, bj, bk, bx, by)'

In [44]:
%%time
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC,LinearSVC
b_score = 0
for i in krn:
    test_svm_mod = SVC(kernel=i)
    test_svm_mod.fit(X_train,y_train.values.ravel())
    accuracy_scr = accuracy_score(y_test, test_svm_mod.predict(X_test))
    if b_score < accuracy_scr:
        b_score =  accuracy_scr
        bi = i 
        print(b_score, bi) 
print(b_score, bi,bi,bi,bi,bi)                

0.8540218163839189 linear


C:\Users\Kaushik\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kaushik\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Kaushik\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.8540218163839189 linear linear linear linear linear
Wall time: 26min 34s
